[2024-10-21T00:04:38.481+0000] {processor.py:186} INFO - Started process (PID=160) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:04:38.482+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:04:38.484+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:04:38.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:04:38.532+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:04:38.526+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:04:38.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:04:38.569+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.102 seconds
[2024-10-21T00:05:08.783+0000] {processor.py:186} INFO - Started process (PID=171) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:08.784+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:05:08.787+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:05:08.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:08.820+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:05:08.815+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:05:08.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:08.846+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.070 seconds
[2024-10-21T00:05:39.137+0000] {processor.py:186} INFO - Started process (PID=176) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:39.138+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:05:39.143+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:05:39.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:39.228+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:05:39.216+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:05:39.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:05:39.272+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.145 seconds
[2024-10-21T00:06:09.412+0000] {processor.py:186} INFO - Started process (PID=181) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:09.414+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:06:09.418+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:06:09.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:09.445+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:06:09.440+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:06:09.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:09.481+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.074 seconds
[2024-10-21T00:06:39.686+0000] {processor.py:186} INFO - Started process (PID=186) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:39.688+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:06:39.690+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:06:39.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:39.714+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:06:39.709+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:06:39.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:06:39.751+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.072 seconds
[2024-10-21T00:07:10.049+0000] {processor.py:186} INFO - Started process (PID=191) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:10.050+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:07:10.052+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:07:10.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:10.078+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:07:10.074+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:07:10.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:10.101+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.057 seconds
[2024-10-21T00:07:40.364+0000] {processor.py:186} INFO - Started process (PID=196) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:40.365+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:07:40.368+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:07:40.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:40.392+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:07:40.388+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:07:40.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:07:40.419+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.061 seconds
[2024-10-21T00:08:10.655+0000] {processor.py:186} INFO - Started process (PID=201) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:10.657+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:08:10.659+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:08:10.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:10.689+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:08:10.684+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:08:10.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:10.712+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.062 seconds
[2024-10-21T00:08:40.987+0000] {processor.py:186} INFO - Started process (PID=206) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:40.989+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:08:40.991+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:08:40.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:41.017+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:08:41.013+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:08:41.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:08:41.038+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.057 seconds
[2024-10-21T00:09:11.272+0000] {processor.py:186} INFO - Started process (PID=211) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:11.273+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:09:11.275+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:09:11.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:11.302+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:09:11.297+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:09:11.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:11.328+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.062 seconds
[2024-10-21T00:09:41.632+0000] {processor.py:186} INFO - Started process (PID=216) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:41.633+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:09:41.636+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:09:41.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:41.660+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:09:41.656+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:09:41.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:09:41.687+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.061 seconds
[2024-10-21T00:10:11.908+0000] {processor.py:186} INFO - Started process (PID=221) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:11.909+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:10:11.912+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:10:11.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:11.935+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:10:11.931+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:10:11.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:11.964+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:10:42.220+0000] {processor.py:186} INFO - Started process (PID=226) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:42.222+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:10:42.225+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:10:42.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:42.249+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:10:42.244+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:10:42.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:10:42.277+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:11:12.516+0000] {processor.py:186} INFO - Started process (PID=238) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:12.517+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:11:12.520+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:12.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:12.544+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:12.540+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:11:12.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:12.573+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:11:42.818+0000] {processor.py:186} INFO - Started process (PID=243) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:42.819+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:11:42.822+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:42.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:42.848+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:42.844+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:11:42.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:42.886+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.074 seconds
[2024-10-21T00:11:55.993+0000] {processor.py:186} INFO - Started process (PID=248) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:55.995+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:11:55.997+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:55.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:56.043+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:11:56.037+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:11:56.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:11:56.066+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.079 seconds
[2024-10-21T00:12:26.297+0000] {processor.py:186} INFO - Started process (PID=253) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:26.299+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:12:26.302+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:12:26.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:26.326+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:12:26.323+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:12:26.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:26.353+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:12:56.614+0000] {processor.py:186} INFO - Started process (PID=258) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:56.616+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:12:56.620+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:12:56.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:56.644+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:12:56.640+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:12:56.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:12:56.673+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.066 seconds
[2024-10-21T00:13:26.917+0000] {processor.py:186} INFO - Started process (PID=263) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:26.919+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:13:26.921+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:13:26.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:26.947+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:13:26.943+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:13:26.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:26.975+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:13:57.222+0000] {processor.py:186} INFO - Started process (PID=268) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:57.224+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:13:57.227+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:13:57.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:57.253+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:13:57.249+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:13:57.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:13:57.281+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.065 seconds
[2024-10-21T00:14:27.689+0000] {processor.py:186} INFO - Started process (PID=273) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:27.697+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:14:27.708+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:14:27.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:27.812+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:14:27.797+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:14:27.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:27.960+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.335 seconds
[2024-10-21T00:14:58.177+0000] {processor.py:186} INFO - Started process (PID=278) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:58.190+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:14:58.211+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:14:58.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:58.280+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:14:58.274+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:14:58.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:14:58.415+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.375 seconds
[2024-10-21T00:15:28.584+0000] {processor.py:186} INFO - Started process (PID=283) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:28.586+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:15:28.589+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:15:28.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:28.641+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:15:28.635+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:15:28.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:28.734+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.155 seconds
[2024-10-21T00:15:58.969+0000] {processor.py:186} INFO - Started process (PID=288) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:58.970+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:15:58.972+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:15:58.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:59.000+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:15:58.996+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:15:59.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:15:59.096+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.133 seconds
[2024-10-21T00:16:29.296+0000] {processor.py:186} INFO - Started process (PID=293) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:29.298+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:16:29.301+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:16:29.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:29.333+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:16:29.328+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:16:29.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:29.421+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.131 seconds
[2024-10-21T00:16:59.669+0000] {processor.py:186} INFO - Started process (PID=298) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:59.671+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:16:59.674+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:16:59.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:59.702+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:16:59.697+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:16:59.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:16:59.792+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.129 seconds
[2024-10-21T00:17:29.970+0000] {processor.py:186} INFO - Started process (PID=303) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:17:29.971+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:17:29.974+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:17:29.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:17:30.009+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:17:30.003+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:17:30.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:17:30.055+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.091 seconds
[2024-10-21T00:18:00.356+0000] {processor.py:186} INFO - Started process (PID=308) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:00.357+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:18:00.359+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:18:00.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:00.386+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:18:00.382+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:18:00.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:00.421+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.072 seconds
[2024-10-21T00:18:30.641+0000] {processor.py:186} INFO - Started process (PID=313) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:30.645+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:18:30.648+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:18:30.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:30.673+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:18:30.668+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:18:30.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:18:30.700+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.064 seconds
[2024-10-21T00:19:00.975+0000] {processor.py:186} INFO - Started process (PID=318) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:00.976+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:00.980+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:00.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:01.052+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:01.046+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:19:01.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:01.086+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.118 seconds
[2024-10-21T00:19:08.085+0000] {processor.py:186} INFO - Started process (PID=323) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:08.087+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:08.090+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:08.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:08.128+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:08.124+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:19:08.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:08.151+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.071 seconds
[2024-10-21T00:19:13.247+0000] {processor.py:186} INFO - Started process (PID=328) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:13.248+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:13.251+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:13.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:13.301+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:13.295+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:19:13.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:13.326+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.085 seconds
[2024-10-21T00:19:18.321+0000] {processor.py:186} INFO - Started process (PID=333) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:18.323+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:18.325+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:18.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:18.362+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:18.359+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 11, in <module>
    from weather_extractor import main as weather_pipeline
ModuleNotFoundError: No module named 'weather_extractor'
[2024-10-21T00:19:18.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:18.386+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.071 seconds
[2024-10-21T00:19:28.516+0000] {processor.py:186} INFO - Started process (PID=338) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:28.517+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:28.520+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:28.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:28.555+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:28.548+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:19:28.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:28.578+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.068 seconds
[2024-10-21T00:19:30.563+0000] {processor.py:186} INFO - Started process (PID=343) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:30.564+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:30.566+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:30.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:30.597+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:30.592+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), './scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:19:30.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:30.629+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.073 seconds
[2024-10-21T00:19:31.668+0000] {processor.py:186} INFO - Started process (PID=348) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:31.669+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:19:31.673+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:31.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:31.710+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:19:31.705+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:19:31.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:19:31.799+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.137 seconds
[2024-10-21T00:20:01.954+0000] {processor.py:186} INFO - Started process (PID=353) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:01.957+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:20:01.959+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:20:01.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:01.982+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:20:01.977+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:20:01.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:02.009+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:20:32.228+0000] {processor.py:186} INFO - Started process (PID=358) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:32.230+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:20:32.232+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:20:32.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:32.256+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:20:32.251+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:20:32.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:20:32.336+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.114 seconds
[2024-10-21T00:21:02.623+0000] {processor.py:186} INFO - Started process (PID=363) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:02.625+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:21:02.628+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:21:02.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:02.651+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:21:02.646+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:21:02.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:02.791+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.173 seconds
[2024-10-21T00:21:32.901+0000] {processor.py:186} INFO - Started process (PID=368) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:32.902+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:21:32.906+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:21:32.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:32.928+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:21:32.924+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:21:32.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:21:32.960+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.066 seconds
[2024-10-21T00:22:03.175+0000] {processor.py:186} INFO - Started process (PID=373) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:03.176+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:22:03.179+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:03.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:03.201+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:03.196+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/scripts'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:22:03.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:03.228+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.058 seconds
[2024-10-21T00:22:21.409+0000] {processor.py:186} INFO - Started process (PID=378) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:21.411+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:22:21.413+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:21.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:21.441+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:21.436+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:22:21.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:21.466+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:22:51.687+0000] {processor.py:186} INFO - Started process (PID=383) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:51.689+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:22:51.691+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:51.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:51.712+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:22:51.708+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:22:51.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:22:51.736+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.055 seconds
[2024-10-21T00:23:22.028+0000] {processor.py:186} INFO - Started process (PID=388) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:22.030+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:23:22.032+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:23:22.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:22.058+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:23:22.052+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:23:22.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:22.084+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.061 seconds
[2024-10-21T00:23:52.339+0000] {processor.py:186} INFO - Started process (PID=393) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:52.341+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:23:52.344+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:23:52.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:52.370+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:23:52.365+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:23:52.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:23:52.407+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.074 seconds
[2024-10-21T00:24:22.679+0000] {processor.py:186} INFO - Started process (PID=398) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:22.680+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:24:22.683+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:24:22.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:22.707+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:24:22.702+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:24:22.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:22.739+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.065 seconds
[2024-10-21T00:24:52.989+0000] {processor.py:186} INFO - Started process (PID=403) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:52.991+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:24:52.994+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:24:52.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:53.018+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:24:53.013+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:24:53.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:24:53.061+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.078 seconds
[2024-10-21T00:25:23.385+0000] {processor.py:186} INFO - Started process (PID=408) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:23.386+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:25:23.389+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:25:23.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:23.411+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:25:23.407+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:25:23.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:23.445+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.066 seconds
[2024-10-21T00:25:53.695+0000] {processor.py:186} INFO - Started process (PID=413) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:53.697+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:25:53.701+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:25:53.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:53.726+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:25:53.720+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:25:53.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:25:53.752+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.063 seconds
[2024-10-21T00:26:24.021+0000] {processor.py:186} INFO - Started process (PID=418) to work on /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:26:24.023+0000] {processor.py:914} INFO - Processing file /app/airflow/dags/weather_pipeline_dag.py for tasks to queue
[2024-10-21T00:26:24.025+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:26:24.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:26:24.049+0000] {logging_mixin.py:190} INFO - [2024-10-21T00:26:24.044+0000] {dagbag.py:387} ERROR - Failed to import: /app/airflow/dags/weather_pipeline_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/weather_pipeline_dag.py", line 8, in <module>
    sys.path.insert(os.path.join(os.path.dirname(os.path.abspath(__file__)), '/'))
TypeError: insert expected 2 arguments, got 1
[2024-10-21T00:26:24.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /app/airflow/dags/weather_pipeline_dag.py
[2024-10-21T00:26:24.074+0000] {processor.py:208} INFO - Processing /app/airflow/dags/weather_pipeline_dag.py took 0.058 seconds
